fi3ework/vite-plugin-checker

- README.md
fix: VlsChecker is just named export, just update README
> docs: VlsChecker is just named export

- packages/vite-plugin-checker/src/main.ts
> fix: wait for all checkers to finish during build

- packages/vite-plugin-checker/src/checkers/typescript/main.ts
> fix: TS checker should respect custom tsconfig

- packages/vite-plugin-checker/__tests__/unit/__snapshots__/logger.spec.ts.snap
- packages/vite-plugin-checker/__tests__/unit/fixtures/eslintDiagnostic.ts
- packages/vite-plugin-checker/__tests__/unit/logger.spec.ts
- packages/vite-plugin-checker/src/logger.ts
> Fix warning level logging

- packages/vite-plugin-checker/__tests__/unit/__snapshots__/logger.spec.ts.snap
- packages/vite-plugin-checker/__tests__/unit/fixtures/eslintDiagnostic.ts
- packages/vite-plugin-checker/__tests__/unit/logger.spec.ts
- packages/vite-plugin-checker/src/logger.ts
@fgblomqvist Sorry I made a mistake to force push to your branch and I recreate a PR. 😅
> fix: eslint normalization

- package.json
- packages/vite-plugin-checker/src/Checker.ts
- packages/vite-plugin-checker/src/checkers/eslint/main.ts
- playground/vanilla-ts/__tests__/__snapshots__/test.spec.ts.snap
- playground/vanilla-ts/__tests__/test.spec.ts
- pnpm-lock.yaml
> fix(eslint): do not flush existing errors on changing file

- packages/vite-plugin-checker/src/checkers/vls/initParams.ts
fix #56 
VTI's configuration is a bit outdated. Copied a newer one from VLS.
https://github.com/vuejs/vetur/blob/387405148312c3bd4bbe6e71845878d9e931ef11/server/src/config.ts#L28-L82
> fix(vls): enable VLS check features

- packages/vite-plugin-checker/src/Checker.ts
- packages/vite-plugin-checker/src/DiagnosticCache.ts
- packages/vite-plugin-checker/src/checkers/eslint/main.ts
- packages/vite-plugin-checker/src/checkers/typescript/main.ts
- packages/vite-plugin-checker/src/checkers/vls/diagnostics.ts
- packages/vite-plugin-checker/src/checkers/vueTsc/main.ts
> fix(vls): should preserve error after editing file without error

- package.json
- packages/runtime/README.md
- packages/runtime/package.json
- packages/runtime/public/index.html
- packages/runtime/scripts/build.js
- packages/runtime/src/App.svelte
- packages/runtime/src/components/Badge.svelte
- packages/runtime/src/components/List.svelte
- packages/runtime/src/main-local.js
- packages/vite-plugin-checker/package.json
- packages/vite-plugin-checker/src/checkers/eslint/main.ts
- packages/vite-plugin-checker/src/types.ts
This will make overlay much more convenient by a float mode instead of an urgent overlay to stop users' all operation. (heavily inspired by react-query's devtool UI)
> feat: rewrite overlay

- packages/vite-plugin-checker/src/main.ts
https://github.com/fi3ework/vite-plugin-checker/issues/108
> fix: show warning for version below vite@2.6.8

- README.md
- packages/vite-plugin-checker/__tests__/e2e/Sandbox/Sandbox.ts
- packages/vite-plugin-checker/src/checkers/eslint/main.ts
- packages/vite-plugin-checker/src/checkers/typescript/main.ts
- packages/vite-plugin-checker/src/checkers/vls/diagnostics.ts
- packages/vite-plugin-checker/src/checkers/vls/main.ts
- packages/vite-plugin-checker/src/logger.ts
- playground/basic/__tests__/__snapshots__/default.spec.ts.snap
- playground/basic/__tests__/default.spec.ts
- playground/basic/__tests__/no-runtime-code-in-build.spec.ts
- playground/basic/__tests__/overlay-terminal-false.spec.ts
- playground/eslint/__tests__/__snapshots__/config.spec.ts.snap
- playground/eslint/__tests__/__snapshots__/test.spec.ts.snap
- playground/multiple-hmr/__tests__/__snapshots__/test.spec.ts.snap
- playground/multiple-hmr/__tests__/test.spec.ts
- playground/multiple-reload/__tests__/__snapshots__/test.spec.ts.snap
- playground/multiple-reload/__tests__/test.spec.ts
- playground/react-ts/__tests__/__snapshots__/test.spec.ts.snap
- playground/vue2-vls/__tests__/__snapshots__/test.spec.ts.snap
- playground/vue2-vls/__tests__/test.spec.ts
implement https://github.com/fi3ework/vite-plugin-checker/issues/58 for ESLint and VLS checker, TSC diagnostic summary is not modified and colored.
> feat: support diagnostic summary for ESLint & VLS

- docs/introduction/getting-started.md
> docs: Add a note for Vite 3

- netlify.toml
https://www.netlify.com/blog/how-to-use-pnpm-with-netlify-build/
> ci: clean Netlify scripts for pnpm

- packages/vite-plugin-checker/src/main.ts
> fix: avoid running twice in SSR mode

- packages/vite-plugin-checker/src/logger.ts
part of https://github.com/fi3ework/vite-plugin-checker/issues/197
> fix: compatible with jiti

- packages/runtime/src/main.js
- packages/runtime/src/ws.js
- packages/vite-plugin-checker/src/main.ts
> fix: show overlay even runtime is loaded after connection event

- .changeset/good-cherries-jog.md
- packages/vite-plugin-checker/src/checkers/typescript/main.ts
- packages/vite-plugin-checker/src/checkers/vueTsc/main.ts
> fix(ts): able to resolve tsconfig when only root specified

- .changeset/grumpy-pumas-tie.md
- packages/vite-plugin-checker/src/client/index.ts
- packages/vite-plugin-checker/src/main.ts
> fix: respect `server.origin` when provided

- .changeset/light-olives-act.md
- packages/runtime/src/App.ce.vue
- playground/config-overlay-position-style/__tests__/test.spec.ts
- playground/config-overlay-position-style/vite.config.js
> fix: panelStyle not work in runtime

- packages/vite-plugin-checker/src/FileDiagnosticManager.ts
small performance improvement affecting projects with "alot" of "errors"
> perf: small performance improvement for FileDiagnosticManager

- packages/vite-plugin-checker/src/checkers/vueTsc/prepareVueTsc.ts
resolve https://github.com/fi3ework/vite-plugin-checker/pull/352#issuecomment-2212637863
> fix(vue-tsc): sync changeExtension

- packages/vite-plugin-checker/package.json
- packages/vite-plugin-checker/src/checkers/eslint/main.ts
- packages/vite-plugin-checker/src/checkers/stylelint/main.ts
- packages/vite-plugin-checker/src/glob.ts
- pnpm-lock.yaml
closes https://github.com/fi3ework/vite-plugin-checker/pull/407
> chore(deps)!: upgrade to chokidar v4

- packages/vite-plugin-checker/src/checkers/biome/main.ts
- packages/vite-plugin-checker/src/checkers/eslint/main.ts
- packages/vite-plugin-checker/src/checkers/stylelint/main.ts
- packages/vite-plugin-checker/src/checkers/vls/main.ts
- packages/vite-plugin-checker/src/logger.ts
Assign logger level according to level of diagnostic.
resolves #500
> fix: use diagnostic level to choose printing as error/info

- packages/vite-plugin-checker/src/checkers/biome/cli.ts
- packages/vite-plugin-checker/src/checkers/vueTsc/languagePlugins.cjs
- playground/biome-default/__tests__/__snapshots__/test.spec.ts.snap
> fix(biome): fix file changes doesnt clear biome diagnostics
