fi3ework/vite-plugin-checker

- packages/vite-plugin-checker/package.json
- pnpm-lock.yaml
`vite-plugin-checker` is missing its [chalk dependency](https://github.com/fi3ework/vite-plugin-checker/blob/257358fcd9b1ad28d9570c737d335225d8f60296/packages/vite-plugin-checker/src/logger.ts#L1). When using the plugin using Yarn PnP, it was complaining about that.
> Add chalk dependency

- packages/vite-plugin-checker/src/main.ts
> Fix early exit when enableBuild is true

- README.md
- packages/vite-plugin-checker/package.json
- packages/vite-plugin-checker/src/checkers/eslint/cli.js
- packages/vite-plugin-checker/src/checkers/eslint/main.ts
- packages/vite-plugin-checker/src/types.ts
- playground/vanilla-ts/vite.config.ts
- pnpm-lock.yaml
- tsconfig.json
BREAKING CHANGE: eslint configs is changed. We made it full configurable of ESLint and remove all the hard coding config properties in 0.3.x. Now, you are allowed to write lint command which you're more familar with rather than JS config.
> feat: new ESLint config API

- README.md
- packages/vite-plugin-checker/src/checkers/vls/cli.ts
- packages/vite-plugin-checker/src/checkers/vls/diagnostics.ts
- packages/vite-plugin-checker/src/checkers/vls/initParams.ts
- packages/vite-plugin-checker/src/checkers/vls/main.ts
- packages/vite-plugin-checker/src/main.ts
- packages/vite-plugin-checker/src/types.ts
Adds support for configuring VLS. All VLS configuration (that which is defined in `getDefaultVLSConfig`) is candidates for customization. Configuration is passed via CLI arguments in build mode, and by `workerData` in serve mode.
Tested on Windows 10 and Ubuntu 18.04 (via WSL).
Fixes #85.
> Add support for passing configuration to VLS.

- packages/vite-plugin-checker/__tests__/unit/vlsConfig.spec.ts
- packages/vite-plugin-checker/src/checkers/vls/diagnostics.ts
A partial fix for #63.
Suggestions will no longer be logged or overlayed in serve mode. Warnings and errors still are.
> Make log level filters respected in serve/watch mode with VLS.

- packages/vite-plugin-checker/src/main.ts
- packages/vite-plugin-checker/src/types.ts
Hi, maintainers and contributors!
I love the plugin because it's handy and will protect our team from wrong types.
I found an issue and made this PR to fix it.
It would be nice that the PR is merged! 🙏 
Passing options as objects to `server.hmr` raises DataCloneError.
I noticed this when using `storybook-builder-vite`.
```ts
// storybook-build-vite will pass a Server instance to `server.hmr.server` like:
export default defineConfig({
// ...
server: {
hmr: {
server: new http.Server(),
},
},
})
```
```console
error when starting dev server:
DataCloneError: function connectionListener(socket) {
defaultTriggerAsyncIdScope(
getOrSetAsyncId(socket), connectionList...<omitted>...
} could not be cloned.
at Worker.postMessage (internal/worker.js:301:23)
at config …
```
> fix: DataCloneError at worker.postMessage

- packages/vite-plugin-checker/src/checkers/typescript/main.ts
The buildMode flag works great when building project but it is not taken into account when watching (ts errors happening on root project are shown but tsc does not check referenced projects). 
This commit fixes this by using TS Compiler API SolutionBuilder when buildMode is set to true.
> Add support for tsc build option in watch mode

- package.json
- packages/vite-plugin-checker/src/checkers/eslint/main.ts
- packages/vite-plugin-checker/src/checkers/eslint/options.ts
- pnpm-lock.yaml
hi @fi3ework !
#108 
I read your guide and realized this is an eslint problem.
I used eslint 8 in my dependencies, It made raise error to here
https://github.com/fi3ework/vite-plugin-checker/blob/00f243a8588b806e7eb2bfc227f41c48387a2d6a/packages/vite-plugin-checker/src/checkers/eslint/main.ts#L4
because `The /lib entrypoint has been removed` (https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0#-the-lib-entrypoint-has-been-removed)
but they didn't support options api (https://github.com/eslint/eslint/blob/main/lib/unsupported-api.js)
so I thought it need options.ts just like you added cli.ts!
please consider to migrating eslint 8.x.x
thank you!
> (#108 ) fix: support eslint 8

- packages/vite-plugin-checker/package.json
Allows installing the beta versions of Vite 3 ([same range](https://github.com/vitest-dev/vitest/blob/c5d07b844504f78e25f33bf3cac5b12f52886de9/packages/vitest/package.json#L97) as Vitest). Prevents error messages when installing:
```log
npm ERR! Could not resolve dependency:
npm ERR! peer vite@">=2" from vite-plugin-checker@0.4.8
npm ERR! node_modules/vite-plugin-checker
npm ERR!   dev vite-plugin-checker@"^0.4.8" from the root project
```
> Allow Vite 3 beta as peer dependency

- packages/runtime/src/App.svelte
- packages/runtime/src/components/Diagnostic.svelte
The overflow bars catch the eye a lot so i made them show up only when needed, i also added a bit of opacity so that you can see below the overlay, the opacity could be reduced further, blur could be removed or increased too.
Previous:
After:
> Changed overflow style and opacity

- packages/vite-plugin-checker/src/checkers/eslint/main.ts
I started configuring `vite-plugin-checker` for one of my projects today, and I ran into the same issue described in #115. I'm not entirely clear why that issue was closed, as it seemed to me that `vite-plugin-checker` was still trying to lint ignored files, even in the latest release.
This PR updates the ESLint checker to resolve #115 more directly. Now, when a file changes, the plugin calls [`eslint.isPathIgnored`](https://eslint.org/docs/latest/developer-guide/nodejs-api#-eslintispathignoredfilepath) to see if the file has been ignored in the ESLint config. This should avoid the warning.
> Skip running ESLint on ignored files

- packages/vite-plugin-checker/src/checkers/eslint/main.ts
- playground/multiple-hmr/__tests__/test.spec.ts
Having the extensions to filter like defined like this:
```js
eslint: {
lintCommand: 'eslint --ext .js,.ts,.vue ./',
},
```
When updating a file that has a different extension such as `package.json`, it tries to lint the file, which results in errors. This only happens on file changes.
I would have expected ESLint to handle this, but that's not the case. After some discussion they decided to leave this to `ESLint` class users to handle. See https://github.com/eslint/eslint/pull/4465.
> fix: Ignore unknown extensions when running ESLint

- packages/vite-plugin-checker/src/checkers/typescript/main.ts
**Context**
This PR is a small patch to the behavior when both `buildMode` and `tsConfigPath` options are used together.
This patch is a workaround for a larger use-case.
**Use case**
- For local dev (i.e. `vite`), enable static typechecking w/o emitting any output.
- For building (i.e. `vite build`), emit.
This is possible today with `buildMode`.
The gap is when specifically when building a [library](https://vitejs.dev/guide/build.html#library-mode). In this scenario, vite compiles the typescript but another tool is needed to emit the declaration files. This is because [vite does not generate declaration files for you](https://github.com/vitejs/vite/issues/3461).
`vite-plugin-checker` internally controls the `--noEmit` flag based on whether `buildMode` is true or false. As a result, my …
> fix(typescript): Support custom path in build mode

- packages/vite-plugin-checker/src/main.ts
references https://github.com/vitejs/vite-plugin-react/blob/main/packages/plugin-react/src/index.ts since the runtime injection is quite similar.
> fix: set plugin as force: 'pre'

- packages/runtime/src/ws.js
- packages/vite-plugin-checker/src/main.ts
- playground/config-default/vite.config.js
- playground/vitestSetup.ts
- vitest.config.e2e.ts
Wish I could know #200 earlier. Lots of time is wasted in handling port and dev base calculation, use Vite's native method `import.meta.hot.on` will never have that pain.
Could also fix #189, if Vite can work correctly with a reverse proxy, the plugin will, too.
> fix: use import.meta.hot.on to do client server communication

- packages/vite-plugin-checker/src/Checker.ts
- packages/vite-plugin-checker/src/main.ts
- packages/vite-plugin-checker/src/types.ts
> fix: use Vite's native logger to log and clean screen before log

- packages/vite-plugin-checker/src/checkers/eslint/main.ts
resolve #226
The plugin only does checking so `--fix` will not be supported. Throw error directly and giving out a explicit message to user when trying to add `--fix` to the `lintCommand`.
> fix: throw when using —fix with ESLint

- docs/checkers/vue-tsc.md
They moved the section this was referring to to another place. Also it is only needed for Vue 2 version `2.6.14` and lower to install `@vue/runtime-dom`.
> docs: update vue-tsc vue 2 support section

- docs/configuration/config.md
- packages/vite-plugin-checker/src/main.ts
- packages/vite-plugin-checker/src/types.ts
This MR adds a new optional configuration property `root`
In our project, we want some checkers to run in a different root directory. This property enables us to do so.
```js
checker({
root: path.resolve(__dirname, "../foo"),
typescript: true,
eslint: {
lintCommand: 'eslint "**/*.{js,ts,tsx}" --cache --max-warnings 0',
},
}),
```
> feat: add optional global configuration of root directory

- .changeset/gentle-singers-poke.md
- packages/vite-plugin-checker/package.json
- packages/vite-plugin-checker/src/main.ts
- pnpm-lock.yaml
fixes https://github.com/fi3ework/vite-plugin-checker/issues/297
- removes package `lodash.debounce` (I could not find any use of this package)
- removes package `lodash.pick` in favor of `lodash` (see https://lodash.com/per-method-packages)
> Remove lodash per method packages

- .changeset/empty-planes-smash.md
- packages/runtime/src/App.ce.vue
I am using this plugin in an RTL project (Persian, Arabic, and... are RTL for example and we have `<html dir='rtl'>`), and when the vite-plugin-checker shows up, its direction is not working properly and messages are hard to read. This is a tiny change to solve this issue and always LTR direction for the message area. You can see the problem here:
Issue:
After this change:
> chore: add direction ltr

- .changeset/curvy-starfishes-beam.md
- packages/vite-plugin-checker/package.json
- packages/vite-plugin-checker/src/main.ts
- pnpm-lock.yaml
It looks like [the move to lodash-es](https://github.com/fi3ework/vite-plugin-checker/pull/299) actually [broke things](https://github.com/fi3ework/vite-plugin-checker/issues/302) (and I kind of feel responsible for that)
It turns out this project has a dependency on lodash for a single use of `pick()`.
Let's remove lodash? What do you think?
> Remove lodash

- .github/dependabot.yml
See [Configuring Dependabot version updates](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates) for more info.
> chore: add dependabot configuration (#265)

- .changeset/smooth-bags-grow.md
- package.json
- packages/runtime/package.json
- playground/backend-integration/package.json
- playground/config-default/package.json
- playground/config-enableBuild-false/package.json
- playground/config-initialIsOpen-error-warnings/package.json
- playground/config-initialIsOpen-error/package.json
- playground/config-initialIsOpen-false/package.json
- playground/config-no-runtime-in-build/package.json
- playground/config-overlay-changes/package.json
- playground/config-overlay-false/package.json
- playground/config-overlay-position-style/package.json
- playground/config-terminal-false/package.json
- playground/eslint-config-log-level/package.json
- playground/eslint-default/package.json
- playground/eslint-flat/package.json
- playground/multiple-hmr/package.json
- playground/multiple-reload/package.json
- playground/stylelint-default/package.json
- playground/typescript-react/package.json
- playground/vls-vue2/package.json
- playground/vue-tsc-vue3/package.json
- pnpm-lock.yaml
fix #346 
As per https://vuejs.org/api/compile-time-flags.html#vite, newer version of @vitejs/plugin-vue has set a default value so there will no longer this warning.
> fix: bump @vitejs/plugin-vue to build runtime

- .changeset/tiny-impalas-cheat.md
- packages/vite-plugin-checker/src/checkers/vueTsc/prepareVueTsc.ts
Ref https://github.com/fi3ework/vite-plugin-checker/issues/306#issuecomment-2199808884.
> fix(vue-tsc): throw error and hint user when vue-tsc working with typescript lower than 5.0.0

- .changeset/unlucky-keys-kneel.md
- packages/vite-plugin-checker/src/checkers/vueTsc/prepareVueTsc.ts
resolve https://github.com/fi3ework/vite-plugin-checker/issues/351
sync up with https://github.com/volarjs/volar.js/blob/630f31118d3986c00cc730eb83cd896709fd547e/packages/typescript/lib/quickstart/runTsc.ts
> fix(vue-tsc): sync up runTsc

- .github/workflows/sync-volar.yml
Add a cronjob to hint syncing up with Volar, to reduce manually check. https://github.com/fi3ework/vite-plugin-checker/issues/351
The cron job will run every midnight, check if `runTsc.ts` changed in last 24 hours. If so, create an issue to hint syncing up.
> ci: add cron job to sync up with Volar

- .changeset/violet-moons-shake.md
- packages/vite-plugin-checker/__tests__/codeFrame.spec.ts
- packages/vite-plugin-checker/src/codeFrame.ts
- packages/vite-plugin-checker/src/logger.ts
- playground/vls-vue2/__tests__/__snapshots__/test.spec.ts.snap
De-duplicate logic used to convert diagnostics location to babel compatible location
- add missing unit tests
- use `codeFrame.ts` in logger
- vue-vls: will format output with same indentation as other checkers
- tiny optimization when generating errors from tsc/vue-tsc
> refactor: reuse codeFrame helper in logger and deduplicate code

- packages/runtime/src/components/Checker.ce.vue
this fixes a bug with this plugin where the file paths & line numbers don't update correctly after a hot reload. the error message for each entry does update while the file paths confusingly don't, therefore creating an incorrect list of errors.
> fix(ui): use a Vue key so file paths update correctly

- playground/config-no-runtime-in-build/__tests__/test.spec.ts
seems https://github.com/fi3ework/vite-plugin-checker/commit/ba9bbc8359c36905fafa0ab3eff751f669419966 caused a regression on windows tests (hanging)
> test: use `globSync`

- package.json
- playground/backend-integration/package.json
- playground/backend-integration/src/main.tsx
- playground/multiple-hmr/package.json
- playground/multiple-hmr/src/main.tsx
- playground/stylelint-default/package.json
- playground/typescript-react/package.json
- playground/typescript-react/src/main.tsx
- playground/vls-vue2/package.json
- pnpm-lock.yaml
this bumps non-eslint-related deps in the playgrounds + workspace
> chore(deps): bump `tinyglobby`, upgrade to react v19, etc.

- packages/vite-plugin-checker/src/checkers/biome/main.ts
- packages/vite-plugin-checker/src/checkers/eslint/main.ts
- packages/vite-plugin-checker/src/checkers/stylelint/main.ts
- packages/vite-plugin-checker/src/checkers/typescript/main.ts
- packages/vite-plugin-checker/src/checkers/vls/main.ts
- packages/vite-plugin-checker/src/checkers/vueTsc/main.ts
- packages/vite-plugin-checker/src/logger.ts
- packages/vite-plugin-checker/src/main.ts
- packages/vite-plugin-checker/src/types.ts
resolves https://github.com/fi3ework/vite-plugin-checker/issues/238
> fix: do not use `error` level for info/warn messages

- docs/checkers/eslint.md
- docs/checkers/stylelint.md
- packages/vite-plugin-checker/src/checkers/eslint/main.ts
- packages/vite-plugin-checker/src/checkers/stylelint/main.ts
- packages/vite-plugin-checker/src/types.ts
Fixes #511
This happens because chokidar watches the entire project root directory, leading to excessive file handle usage in large projects.
Added a new `watchPath` option for ESLint (and Stylelint) checkers that allows users to specify a specific directory to watch instead of the entire project root.
**Key Changes:**
1. **New Configuration Option**: Added `watchPath?: string` to ESLint and Stylelint type definitions
2. **Targeted File Watching**: When `watchPath` is specified, chokidar only watches that specific directory
3. **Backward Compatibility**: When `watchPath` is not specified, behaves exactly as before (watches entire root)
4. **Documentation**: Added examples and performance optimization guides
> feat: add `watchPath` option to resolve EMFILE errors

- packages/vite-plugin-checker/src/main.ts
Fixes #535 
```
[DEP0190] DeprecationWarning:  Passing args to a child process with shell option true can lead to security vulnerabilities, as the arguments are not escaped, only concatenated.
```
> Fix node 24 deprecation with `spawn()` args (fixes #535)

- packages/runtime/src/components/Diagnostic.ce.vue
This fixes a bug where the `codeFrameRE` regex will sometimes return false when `test(frame)` is run, because the `lastIndex` is not being reset before each use.  This causes a bug where the code frame will sometimes not display in the overlay.
> fix(runtime): reset lastIndex before reusing regexes
